const elements = [
    { number: 1, name: "水素", symbol: "H", weight: "1.008", state: "gas", x: 1, y: 1 },
    { number: 2, name: "ヘリウム", symbol: "He", weight: "4.0026", state: "gas", x: 18, y: 1 },
    { number: 3, name: "リチウム", symbol: "Li", weight: "6.94", state: "solid", x: 1, y: 2 },
    { number: 4, name: "ベリリウム", symbol: "Be", weight: "9.0122", state: "solid", x: 2, y: 2 },
    { number: 5, name: "ホウ素", symbol: "B", weight: "10.81", state: "solid", x: 13, y: 2 },
    { number: 6, name: "炭素", symbol: "C", weight: "12.011", state: "solid", x: 14, y: 2 },
    { number: 7, name: "窒素", symbol: "N", weight: "14.007", state: "gas", x: 15, y: 2 },
    { number: 8, name: "酸素", symbol: "O", weight: "15.999", state: "gas", x: 16, y: 2 },
    { number: 9, name: "フッ素", symbol: "F", weight: "18.998", state: "gas", x: 17, y: 2 },
    { number: 10, name: "ネオン", symbol: "Ne", weight: "20.180", state: "gas", x: 18, y: 2 },
    { number: 11, name: "ナトリウム", symbol: "Na", weight: "22.990", state: "solid", x: 1, y: 3 },
    { number: 12, name: "マグネシウム", symbol: "Mg", weight: "24.305", state: "solid", x: 2, y: 3 },
    { number: 13, name: "アルミニウム", symbol: "Al", weight: "26.982", state: "solid", x: 13, y: 3 },
    { number: 14, name: "ケイ素", symbol: "Si", weight: "28.085", state: "solid", x: 14, y: 3 },
    { number: 15, name: "リン", symbol: "P", weight: "30.974", state: "solid", x: 15, y: 3 },
    { number: 16, name: "硫黄", symbol: "S", weight: "32.06", state: "solid", x: 16, y: 3 },
    { number: 17, name: "塩素", symbol: "Cl", weight: "35.45", state: "gas", x: 17, y: 3 },
    { number: 18, name: "アルゴン", symbol: "Ar", weight: "39.948", state: "gas", x: 18, y: 3 },
    { number: 19, name: "カリウム", symbol: "K", weight: "39.098", state: "solid", x: 1, y: 4 },
    { number: 20, name: "カルシウム", symbol: "Ca", weight: "40.078", state: "solid", x: 2, y: 4 },
    { number: 21, name: "スカンジウム", symbol: "Sc", weight: "44.956", state: "solid", x: 3, y: 4 },
    { number: 22, name: "チタン", symbol: "Ti", weight: "47.867", state: "solid", x: 4, y: 4 },
    { number: 23, name: "バナジウム", symbol: "V", weight: "50.9415", state: "solid", x: 5, y: 4 },
    { number: 24, name: "クロム", symbol: "Cr", weight: "51.9961", state: "solid", x: 6, y: 4 },
    { number: 25, name: "マンガン", symbol: "Mn", weight: "54.9380", state: "solid", x: 7, y: 4 },
    { number: 26, name: "鉄", symbol: "Fe", weight: "55.845", state: "solid", x: 8, y: 4 },
    { number: 27, name: "コバルト", symbol: "Co", weight: "58.9332", state: "solid", x: 9, y: 4 },
    { number: 28, name: "ニッケル", symbol: "Ni", weight: "58.6934", state: "solid", x: 10, y: 4 },
    { number: 29, name: "銅", symbol:"Cu" , weight:"63.546" , state:"solid" , x :11 , y :4},
    { number: 30 , name:"亜鉛" , symbol:"Zn" , weight:"65.38" , state:"solid" , x :12 , y :4},
    { number: 31, name: "ガリウム", symbol: "Ga", weight: "69.723", state: "solid", x: 13, y: 4 },
    { number: 32, name: "ゲルマニウム", symbol: "Ge", weight: "72.630", state: "solid", x: 14, y: 4 },
    { number: 33, name: "ヒ素", symbol: "As", weight: "74.9216", state: "solid", x: 15, y: 4 },
    { number: 34, name: "セレン", symbol: "Se", weight: "78.971", state: "solid", x: 16, y: 4 },
    { number: 35, name: "臭素", symbol: "Br", weight: "79.904", state: "liquid", x: 17, y: 4 },
    { number: 36, name: "クリプトン", symbol: "Kr", weight: "83.798", state: "gas", x: 18, y: 4 },
    { number: 37, name: "ルビジウム", symbol: "Rb", weight: "85.4678", state: "solid", x: 1, y: 5 },
    { number: 38, name: "ストロンチウム", symbol: "Sr", weight: "87.62", state: "solid", x: 2, y: 5 },
    { number: 39, name: "イットリウム", symbol: "Y", weight: "88.905", state: "solid", x: 3, y: 5 },
    { number: 40, name: "ジルコニウム", symbol: "Zr", weight: "91.224", state: "solid", x: 4, y: 5 },
    { number: 41, name: "ニオブ", symbol: "Nb", weight: "92.906", state: "solid", x: 5, y: 5 },
    { number: 42, name: "モリブデン", symbol: "Mo", weight: "95.95", state: "solid", x: 6, y: 5 },
    { number: 43, name: "テクネチウム", symbol: "Tc", weight: "(98)", state: "solid", x: 7, y: 5 },
    { number: 44, name: "ルテニウム", symbol: "Ru", weight: "101.07", state: "solid", x: 8, y: 5 },
    { number: 45, name: "ロジウム", symbol: "Rh", weight: "102.90550", state: "solid", x: 9, y: 5 },
    { number: 46, name: "パラジウム", symbol: "Pd", weight:"106.42" , state:"solid" , x :10 , y :5},
    { number: 47 , name:"銀" , symbol:"Ag" , weight:"107.8682" , state:"solid" , x :11 , y :5},
    { number: 48, name:"カドミウム" , symbol:"Cd" , weight:"112.414" , state:"solid" , x :12 , y :5},
    { number: 49, name:"インジウム" , symbol:"In" , weight:"114.818" , state:"solid" , x :13 , y :5},
    { number: 50, name:"スズ" , symbol:"Sn" , weight:"118.710" , state:"solid" , x :14 , y :5},
    { number: 51, name:"アンチモン" , symbol:"Sb" , weight:"121.760" , state:"solid" , x :15 , y :5},
    { number: 52, name:"テルル" , symbol:"Te" , weight:"127.60" , state:"solid" , x :16 , y :5},
    { number: 53, name:"ヨウ素" , symbol:"I" , weight:"126.90447" , state:"solid" , x :17 , y :5},
    { number: 54, name:"キセノン" , symbol:"Xe" , weight:"131.293" , state:"gas" , x :18 , y :5},
    { number: 55, name: "セシウム", symbol: "Cs", weight: "132.905", state: "solid", x: 1, y: 6 },
    { number: 56, name: "バリウム", symbol: "Ba", weight: "137.327", state: "solid", x: 2, y: 6 },
    { number: 57, name: "ランタン", symbol: "La", weight: "138.91", state: "solid", x: 3, y: 8 },
    { number: 58, name: "セリウム", symbol: "Ce", weight: "140.116", state: "solid", x: 4, y: 8 },
    { number: 59, name: "プラセオジム", symbol: "Pr", weight: "140.90766", state: "solid", x: 5, y: 8 },
    { number: 60, name: "ネオジム", symbol: "Nd", weight: "144.242", state: "solid", x: 6, y: 8 },
    { number: 61, name: "プロメチウム", symbol: "Pm", weight: "(145)", state: "solid", x: 7, y: 8 },
    { number: 62, name: "サマリウム", symbol: "Sm", weight: "150.36", state: "solid", x: 8, y: 8 },
    { number: 63, name: "ユウロピウム", symbol: "Eu", weight:"151.964" , state:"solid" , x :9 , y :8},
    { number: 64 , name:"ガドリニウム" , symbol:"Gd" , weight:"157.25" , state:"solid" , x :10 , y :8},
    { number: 65 , name:"テルビウム" , symbol:"Tb" , weight:"158.92535" , state:"solid" , x :11 , y :8},
    { number: 66 , name:"ジスプロシウム" , symbol:"Dy" , weight:"162.500" , state:"solid" , x :12 , y :8},
    { number: 67, name:"ホルミウム" , symbol:"Ho" , weight:"164.93033" , state:"solid" , x :13 , y :8},
    { number: 68, name:"エルビウム" , symbol:"Er" , weight:"167.259" , state:"solid" , x :14 , y :8},
    { number: 69, name:"チタニウム" , symbol:"Tm" , weight:"168.93422" , state:"solid" , x :15 , y :8},
    { number: 70, name:"イッテルビウム", symbol: "Yb", weight: "173.04", state: "solid", x: 16, y: 8 },
    { number: 71, name: "ルテチウム", symbol: "Lu", weight: "174.9668", state: "solid", x: 17, y: 8 },
    { number: 72, name: "ハフニウム", symbol: "Hf", weight: "178.49", state: "solid", x: 4, y: 6 },
    { number: 73, name: "タンタル", symbol: "Ta", weight: "180.947", state: "solid", x: 5, y: 6 },
    { number: 74, name: "タングステン", symbol: "W", weight: "183.84", state: "solid", x: 6, y: 6 },
    { number: 75, name: "レニウム", symbol: "Re", weight: "186.207", state: "solid", x: 7, y: 6 },
    { number: 76, name: "オスミウム", symbol: "Os", weight: "190.23", state: "solid", x: 8, y: 6 },
    { number: 77, name: "イリジウム", symbol: "Ir", weight: "192.217", state: "solid", x: 9, y: 6 },
    { number: 78, name: "白金", symbol: "Pt", weight: "195.084", state: "solid", x: 10, y: 6 },
    { number: 79, name: "金", symbol: "Au", weight: "196.966569", state: "solid", x: 11, y: 6 },
    { number: 80, name: "水銀", symbol: "Hg", weight: "200.592", state: "liquid", x: 12, y: 6 },
    { number: 81, name: "タリウム", symbol: "Tl", weight: "204.38", state: "solid", x: 13, y: 6 },
    { number: 82, name: "鉛", symbol: "Pb", weight: "207.2", state: "solid", x: 14, y: 6 },
    { number: 83, name: "ビスマス", symbol: "Bi", weight: "208.98040", state: "solid", x: 15, y: 6 },
    { number: 84, name: "ポロニウム", symbol: "Po", weight: "(209)", state: "solid", x: 16, y: 6 },
    { number: 85, name: "アスタチン", symbol: "At", weight: "(210)", state: "solid", x: 17, y: 6 },
    { number: 86, name: "ラドン", symbol: "Rn", weight: "(222)", state: "gas", x: 18, y: 6 },
    { number: 87, name: "フランシウム", symbol: "Fr", weight: "(223)", state: "solid", x: 1, y: 7 },
    { number: 88, name: "ラジウム", symbol: "Ra", weight: "(226)", state: "solid", x: 2, y: 7 },
    { number: 89, name: "アクチニウム", symbol: "Ac", weight: "227", state: "solid", x: 3, y: 9 },
    { number: 90, name: "トリウム", symbol: "Th", weight: "232.038", state: "solid", x: 4, y: 9 },
    { number: 91, name: "プロトアクチニウム", symbol: "Pa", weight: "231.03588", state: "solid", x: 5, y: 9 },
    { number: 92, name: "ウラン", symbol: "U", weight: "238.02891", state: "solid", x: 6, y: 9 },
    { number: 93, name: "ネプツニウム", symbol: "Np", weight: "(237)", state: "solid", x: 7, y: 9 },
    { number: 94, name: "プルトニウム", symbol: "Pu", weight: "(244)", state: "solid", x: 8, y: 9 },
    { number: 95, name:"アメリシウム" , symbol:"Am" , weight:"243" , state:"solid" , x :9 , y :9},
    { number: 96 , name:"キュリウム" , symbol:"Cm" , weight:"247" , state:"solid" , x :10 , y :9},
    { number: 97 , name:"バークリウム" , symbol:"Bk" , weight:"247" , state:"solid" , x :11 , y :9},
    { number: 98, name:"カリフォルニウム" , symbol:"Cf" , weight:"251" , state:"solid" , x :12 , y :9},
    { number: 99, name:"アインスタイニウム" , symbol:"Es" , weight:"252" , state:"solid" , x :13 , y :9},
    { number: 100, name:"フェルミウム", symbol:"Fm" , weight:"257" , state:"solid" , x :14 , y :9},
    { number: 101, name:"メンデレビウム", symbol:"Md" , weight:"258" , state:"solid" , x :15 , y :9},
    { number: 102, name:"ノーベリウム", symbol: "No", weight: "(259)", state: "solid", x: 16, y: 9 },
    { number: 103, name: "ローレンシウム", symbol: "Lr", weight: "(262)", state: "solid", x: 17, y: 9 },
    { number: 104, name: "ラザホージウム", symbol: "Rf", weight: "(267)", state: "solid", x: 4, y: 7 },
    { number: 105, name: "ドブニウム", symbol: "Db", weight: "(270)", state: "solid", x: 5, y: 7 },
    { number: 106, name: "シーボーギウム", symbol: "Sg", weight: "(271)", state: "solid", x: 6, y: 7 },
    { number: 107, name: "ボーリウム", symbol: "Bh", weight: "(270)", state: "solid", x: 7, y: 7 },
    { number: 108, name: "ハッシウム", symbol: "Hs", weight: "(277)", state: "solid", x: 8, y: 7 },
    { number: 109, name: "マイトネリウム", symbol: "Mt", weight: "(276)", state: "solid", x: 9, y: 7 },
    { number: 110, name: "ダームスタチウム", symbol: "Ds", weight: "(281)", state: "solid", x: 10, y: 7 },
    { number: 111, name: "レントゲニウム", symbol: "Rg", weight: "(282)", state: "solid", x: 11, y: 7 },
    { number: 112, name: "コペルニシウム", symbol: "Cn", weight: "(285)", state: "solid", x: 12, y: 7 },
    { number: 113, name: "ニホニウム", symbol: "Nh", weight: "(286)", state: "solid", x: 13, y: 7 },
    { number: 114, name: "フレロビウム", symbol: "Fl", weight: "(289)", state: "solid", x: 14, y: 7 },
    { number: 115, name: "ムスカビウム", symbol: "Mc", weight: "(288)", state: "solid", x: 15, y: 7 },
    { number: 116, name: "リバモリウム", symbol: "Lv", weight: "(293)", state: "solid", x: 16, y: 7 },
    { number: 117, name: "テネシン", symbol: "Ts", weight: "(294)", state: "solid", x: 17, y: 7 },
    { number: 118, name: "オガネソン", symbol: "Og", weight: "(294)", state: "unknown", x: 18, y: 7 }
];